### ISSUE TITLE
agTrend link isn't working

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NMFS-Protected-Species-Tools/nmfs-protected-species-tools.github.io#2]
Hello @ChristineStawitz-NOAA,

The link for **agTrend** on the [Protected Species Tools](https://nmfs-protected-species-tools.github.io/) page isn't working. I got the error message below:
`An error has occurred. Check your logs or contact the app author for clarification.`

Does it need to be updated?

**Comment by HaleyOleynik-NOAA** [comment]
Updated! https://nmfs-fish-tools.github.io/agTrend/
